,url,repository_url,labels_url,comments_url,events_url,html_url,id,node_id,number,title,user,labels,state,locked,assignee,assignees,milestone,comments,created_at,updated_at,closed_at,author_association,active_lock_reason,draft,pull_request,body,reactions,timeline_url,performed_via_github_app
0,https://api.github.com/repos/pandas-dev/pandas/issues/46880,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46880/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46880/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46880/events,https://github.com/pandas-dev/pandas/pull/46880,1216596831,PR_kwDOAA0YD8421ddq,46880,REF: libhashtable.mode support mask,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,0,2022-04-26T23:32:51Z,2022-04-26T23:32:51Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46880', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46880', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46880.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46880.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46880/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46880/timeline,
1,https://api.github.com/repos/pandas-dev/pandas/issues/46879,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46879/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46879/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46879/events,https://github.com/pandas-dev/pandas/pull/46879,1216420925,PR_kwDOAA0YD84203MB,46879,Merge nonstring columns,"{'login': 'ericman93', 'id': 5768348, 'node_id': 'MDQ6VXNlcjU3NjgzNDg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5768348?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/ericman93', 'html_url': 'https://github.com/ericman93', 'followers_url': 'https://api.github.com/users/ericman93/followers', 'following_url': 'https://api.github.com/users/ericman93/following{/other_user}', 'gists_url': 'https://api.github.com/users/ericman93/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/ericman93/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/ericman93/subscriptions', 'organizations_url': 'https://api.github.com/users/ericman93/orgs', 'repos_url': 'https://api.github.com/users/ericman93/repos', 'events_url': 'https://api.github.com/users/ericman93/events{/privacy}', 'received_events_url': 'https://api.github.com/users/ericman93/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,2,2022-04-26T20:05:57Z,2022-04-26T23:16:06Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46879', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46879', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46879.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46879.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46879/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46879/timeline,
2,https://api.github.com/repos/pandas-dev/pandas/issues/46878,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46878/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46878/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46878/events,https://github.com/pandas-dev/pandas/pull/46878,1216314477,PR_kwDOAA0YD8420gmo,46878,PERF: use C version of np.empty,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,1,2022-04-26T18:16:07Z,2022-04-26T22:52:09Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46878', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46878', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46878.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46878.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46878/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46878/timeline,
3,https://api.github.com/repos/pandas-dev/pandas/issues/46877,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46877/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46877/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46877/events,https://github.com/pandas-dev/pandas/issues/46877,1216241042,I_kwDOAA0YD85Ifl2S,46877,BUG: `pd.date_range` not factoring in `nanoseconds` in `freq`,"{'login': 'galipremsagar', 'id': 11664259, 'node_id': 'MDQ6VXNlcjExNjY0MjU5', 'avatar_url': 'https://avatars.githubusercontent.com/u/11664259?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/galipremsagar', 'html_url': 'https://github.com/galipremsagar', 'followers_url': 'https://api.github.com/users/galipremsagar/followers', 'following_url': 'https://api.github.com/users/galipremsagar/following{/other_user}', 'gists_url': 'https://api.github.com/users/galipremsagar/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/galipremsagar/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/galipremsagar/subscriptions', 'organizations_url': 'https://api.github.com/users/galipremsagar/orgs', 'repos_url': 'https://api.github.com/users/galipremsagar/repos', 'events_url': 'https://api.github.com/users/galipremsagar/events{/privacy}', 'received_events_url': 'https://api.github.com/users/galipremsagar/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-26T17:05:27Z,2022-04-26T17:05:27Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
print(pd.__version__)
x = pd.date_range(end='1970-01-01 00:00:00', periods=10, freq=pd.DateOffset(**{'hours': 10, 'days': 57, 'nanoseconds': 3}), name=""a"")
print(x.to_numpy())

1.4.2
['1968-08-02T06:00:00.000000000' '1968-09-28T16:00:00.000000000'
 '1968-11-25T02:00:00.000000000' '1969-01-21T12:00:00.000000000'
 '1969-03-19T22:00:00.000000000' '1969-05-16T08:00:00.000000000'
 '1969-07-12T18:00:00.000000000' '1969-09-08T04:00:00.000000000'
 '1969-11-04T14:00:00.000000000' '1970-01-01T00:00:00.000000000']
```


### Issue Description

While generating date ranges, `nanoseconds` specified in `freq` are not being factored in.

### Expected Behavior

```python
['1968-08-02T06:00:00.000000000', '1968-09-28T16:00:00.000000003',
       '1968-11-25T02:00:00.000000006', '1969-01-21T12:00:00.000000009',
       '1969-03-19T22:00:00.000000012', '1969-05-16T08:00:00.000000015',
       '1969-07-12T18:00:00.000000018', '1969-09-08T04:00:00.000000021',
       '1969-11-04T14:00:00.000000024', '1970-01-01T00:00:00.000000027']
```

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.6.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 21.4.0
Version          : Darwin Kernel Version 21.4.0: Fri Mar 18 00:45:05 PDT 2022; root:xnu-8020.101.4~15/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : en_US.UTF-8
pandas           : 1.3.4
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 59.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 5.0.0
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46877/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46877/timeline,
4,https://api.github.com/repos/pandas-dev/pandas/issues/46876,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46876/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46876/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46876/events,https://github.com/pandas-dev/pandas/issues/46876,1215986762,I_kwDOAA0YD85IenxK,46876,BUG: pd.read_sql returns wrong columns name for specific query,"{'login': 'shentianhao1993', 'id': 66732186, 'node_id': 'MDQ6VXNlcjY2NzMyMTg2', 'avatar_url': 'https://avatars.githubusercontent.com/u/66732186?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/shentianhao1993', 'html_url': 'https://github.com/shentianhao1993', 'followers_url': 'https://api.github.com/users/shentianhao1993/followers', 'following_url': 'https://api.github.com/users/shentianhao1993/following{/other_user}', 'gists_url': 'https://api.github.com/users/shentianhao1993/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/shentianhao1993/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/shentianhao1993/subscriptions', 'organizations_url': 'https://api.github.com/users/shentianhao1993/orgs', 'repos_url': 'https://api.github.com/users/shentianhao1993/repos', 'events_url': 'https://api.github.com/users/shentianhao1993/events{/privacy}', 'received_events_url': 'https://api.github.com/users/shentianhao1993/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-26T13:46:06Z,2022-04-26T13:46:13Z,,NONE,,,,"### Pandas version checks

- [x] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
from sqlalchemy import create_engine
import pandas as pd

uri = 'clickhouse://user:password@host:8123'
engine = create_engine(uri)

sql = """"""
         SELECT 
             partition,
             sum(rows) AS rows,
             formatReadableSize(sum(data_uncompressed_bytes)) AS original_size,
             formatReadableSize(sum(data_compressed_bytes)) AS compressed_size,
             round((sum(data_compressed_bytes) / sum(data_uncompressed_bytes)) * 100, 0) AS compress_rate
         FROM system.parts
         WHERE (database IN ('system')) AND (table IN ('query_log')) AND (partition LIKE '2022-04-%%')
         GROUP BY partition
         ORDER BY partition ASC
         """"""

df = pd.read_sql(sql, con=cengine)
print(df)
```


### Issue Description

   2022-04-22   10124   18.19 MiB   1.11 MiB  6
0  2022-04-24   28892   51.88 MiB   3.16 MiB  6
1  2022-04-25   28800   51.73 MiB   3.14 MiB  6
2  2022-04-26  141150  342.90 MiB  19.50 MiB  6

### Expected Behavior

    partition   rows   original_size   compressed_size  compress_rate
0   2022-04-22   10124   18.19 MiB   1.11 MiB  6
1  2022-04-24   28892   51.88 MiB   3.16 MiB  6
2  2022-04-25   28800   51.73 MiB   3.14 MiB  6
3  2022-04-26  141150  342.90 MiB  19.50 MiB  6

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 945c9ed766a61c7d2c0a7cbb251b6edebf9cb7d5
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19044
machine          : AMD64
processor        : Intel64 Family 6 Model 166 Stepping 0, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.3.4
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.0.4
Cython           : 0.29.24
pytest           : 6.2.4
hypothesis       : None
sphinx           : 4.2.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.1
lxml.etree       : 4.6.3
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.3 (dt dec pq3 ext lo64)
jinja2           : 2.11.3
IPython          : 7.29.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.2
fsspec           : 2021.10.1
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : 2.7.3
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.3.24
tables           : 3.6.1
tabulate         : 0.8.9
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
numba            : 0.54.1

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46876/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46876/timeline,
5,https://api.github.com/repos/pandas-dev/pandas/issues/46875,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46875/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46875/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46875/events,https://github.com/pandas-dev/pandas/pull/46875,1215728353,PR_kwDOAA0YD842yi1z,46875,BUG: extra row created when calling to_excel for multi-index columns,"{'login': 'jackzhenguo', 'id': 20391209, 'node_id': 'MDQ6VXNlcjIwMzkxMjA5', 'avatar_url': 'https://avatars.githubusercontent.com/u/20391209?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jackzhenguo', 'html_url': 'https://github.com/jackzhenguo', 'followers_url': 'https://api.github.com/users/jackzhenguo/followers', 'following_url': 'https://api.github.com/users/jackzhenguo/following{/other_user}', 'gists_url': 'https://api.github.com/users/jackzhenguo/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jackzhenguo/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jackzhenguo/subscriptions', 'organizations_url': 'https://api.github.com/users/jackzhenguo/orgs', 'repos_url': 'https://api.github.com/users/jackzhenguo/repos', 'events_url': 'https://api.github.com/users/jackzhenguo/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jackzhenguo/received_events', 'type': 'User', 'site_admin': False}",[],open,False,,[],,2,2022-04-26T10:16:43Z,2022-04-26T23:18:55Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46875', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46875', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46875.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46875.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.



When multi-level columns are written into excel, use to_ Excel method, there will be an extra row in the saved xlsx file

![image](https://user-images.githubusercontent.com/20391209/165278268-c8319b4f-572b-4b37-8ba8-f0ed4318f053.png)

I tried to fix and welcome to comment for this update.


","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46875/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46875/timeline,
6,https://api.github.com/repos/pandas-dev/pandas/issues/46874,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46874/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46874/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46874/events,https://github.com/pandas-dev/pandas/issues/46874,1215574410,I_kwDOAA0YD85IdDGK,46874,PERF: numpy function like np.max called on DataFrame significantly slower than df.max,"{'login': 'auderson', 'id': 48577571, 'node_id': 'MDQ6VXNlcjQ4NTc3NTcx', 'avatar_url': 'https://avatars.githubusercontent.com/u/48577571?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/auderson', 'html_url': 'https://github.com/auderson', 'followers_url': 'https://api.github.com/users/auderson/followers', 'following_url': 'https://api.github.com/users/auderson/following{/other_user}', 'gists_url': 'https://api.github.com/users/auderson/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/auderson/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/auderson/subscriptions', 'organizations_url': 'https://api.github.com/users/auderson/orgs', 'repos_url': 'https://api.github.com/users/auderson/repos', 'events_url': 'https://api.github.com/users/auderson/events{/privacy}', 'received_events_url': 'https://api.github.com/users/auderson/received_events', 'type': 'User', 'site_admin': False}","[{'id': 8935311, 'node_id': 'MDU6TGFiZWw4OTM1MzEx', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Performance', 'name': 'Performance', 'color': 'a10c02', 'default': False, 'description': 'Memory or execution speed performance'}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,4,2022-04-26T08:11:12Z,2022-04-26T15:19:10Z,,CONTRIBUTOR,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this issue exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this issue exists on the main branch of pandas.


### Reproducible Example

related: #45099

```python
df = pd.DataFrame(np.random.randn(100, 100))
```
```python
%%time
_ = df.max()
```
CPU times: user 913 µs, sys: 1.6 ms, total: 2.52 ms
Wall time: 1.81 ms
```python
%%time
_ = np.max(df)
```
CPU times: user 13.8 ms, sys: 290 µs, total: 14.1 ms
Wall time: 12.8 ms
```python
%%pyinstrument
_ = np.max(df)
```

![image](https://user-images.githubusercontent.com/48577571/165252677-175a1f21-0a09-4ed2-829e-49279b32d848.png)

Looks like this is triggered by:
https://github.com/pandas-dev/pandas/blob/8980af7ce9d98713b0f8792e38f0fe43088e8780/pandas/core/generic.py#L10674-L10683

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 06d230151e6f18fdb8139d09abf539867a8cd481
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.8.0-63-generic
Version          : #71-Ubuntu SMP Tue Jul 13 15:59:12 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.1
numpy            : 1.21.5
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 58.0.4
Cython           : 0.29.28
pytest           : 6.2.5
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.2
psycopg2         : 2.9.3
jinja2           : 3.0.3
IPython          : 8.1.1
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
matplotlib       : 3.5.1
numba            : 0.55.1
numexpr          : 2.8.0
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
sqlalchemy       : 1.4.32
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>


### Prior Performance

_No response_","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46874/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46874/timeline,
7,https://api.github.com/repos/pandas-dev/pandas/issues/46873,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46873/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46873/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46873/events,https://github.com/pandas-dev/pandas/issues/46873,1215290588,I_kwDOAA0YD85Ib9zc,46873,BUG: Error when exporting an empty DataFrame with MultiIndex to xlsx file,"{'login': 'WEGFan', 'id': 7558201, 'node_id': 'MDQ6VXNlcjc1NTgyMDE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7558201?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/WEGFan', 'html_url': 'https://github.com/WEGFan', 'followers_url': 'https://api.github.com/users/WEGFan/followers', 'following_url': 'https://api.github.com/users/WEGFan/following{/other_user}', 'gists_url': 'https://api.github.com/users/WEGFan/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/WEGFan/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/WEGFan/subscriptions', 'organizations_url': 'https://api.github.com/users/WEGFan/orgs', 'repos_url': 'https://api.github.com/users/WEGFan/repos', 'events_url': 'https://api.github.com/users/WEGFan/events{/privacy}', 'received_events_url': 'https://api.github.com/users/WEGFan/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-26T02:47:56Z,2022-04-26T02:47:56Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame(
    index=pd.MultiIndex.from_arrays([[], []], names=['a', 'b']),
    columns=['A', 'B']
)
df.to_excel('test.xlsx')
```


### Issue Description

```
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
Input In [9], in <cell line: 7>()
      1 import pandas as pd
      3 df = pd.DataFrame(
      4     index=pd.MultiIndex.from_arrays([[], []], names=['a', 'b']),
      5     columns=['A', 'B']
      6 )
----> 7 df.to_excel('test.xlsx')

File E:\Program Files\Python39\lib\site-packages\pandas\core\generic.py:2345, in NDFrame.to_excel(self, excel_writer, sheet_name, na_rep, float_format, columns, header, index, index_label, startrow, startcol, engine, merge_cells, encoding, inf_rep, verbose, freeze_panes, storage_options)
   2332 from pandas.io.formats.excel import ExcelFormatter
   2334 formatter = ExcelFormatter(
   2335     df,
   2336     na_rep=na_rep,
   (...)
   2343     inf_rep=inf_rep,
   2344 )
-> 2345 formatter.write(
   2346     excel_writer,
   2347     sheet_name=sheet_name,
   2348     startrow=startrow,
   2349     startcol=startcol,
   2350     freeze_panes=freeze_panes,
   2351     engine=engine,
   2352     storage_options=storage_options,
   2353 )

File E:\Program Files\Python39\lib\site-packages\pandas\io\formats\excel.py:894, in ExcelFormatter.write(self, writer, sheet_name, startrow, startcol, freeze_panes, engine, storage_options)
    891     need_save = True
    893 try:
--> 894     writer.write_cells(
    895         formatted_cells,
    896         sheet_name,
    897         startrow=startrow,
    898         startcol=startcol,
    899         freeze_panes=freeze_panes,
    900     )
    901 finally:
    902     # make sure to close opened file handles
    903     if need_save:

File E:\Program Files\Python39\lib\site-packages\pandas\io\excel\_xlsxwriter.py:227, in XlsxWriter.write_cells(self, cells, sheet_name, startrow, startcol, freeze_panes)
    224 if validate_freeze_panes(freeze_panes):
    225     wks.freeze_panes(*(freeze_panes))
--> 227 for cell in cells:
    228     val, fmt = self._value_with_fmt(cell.val)
    230     stylekey = json.dumps(cell.style)

File E:\Program Files\Python39\lib\site-packages\pandas\io\formats\excel.py:831, in ExcelFormatter.get_formatted_cells(self)
    830 def get_formatted_cells(self) -> Iterable[ExcelCell]:
--> 831     for cell in itertools.chain(self._format_header(), self._format_body()):
    832         cell.val = self._format_value(cell.val)
    833         yield cell

File E:\Program Files\Python39\lib\site-packages\pandas\io\formats\excel.py:630, in ExcelFormatter._format_header_regular(self)
    628     coloffset = 1
    629     if isinstance(self.df.index, MultiIndex):
--> 630         coloffset = len(self.df.index[0])
    632 colnames = self.columns
    633 if self._has_aliases:

File E:\Program Files\Python39\lib\site-packages\pandas\core\indexes\multi.py:2075, in MultiIndex.__getitem__(self, key)
   2073 retval = []
   2074 for lev, level_codes in zip(self.levels, self.codes):
-> 2075     if level_codes[key] == -1:
   2076         retval.append(np.nan)
   2077     else:

IndexError: index 0 is out of bounds for axis 0 with size 0
```

### Expected Behavior

Write a sheet with only column header

### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.7.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19042
machine          : AMD64
processor        : Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : Chinese (Simplified)_China.936

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 57.4.0
Cython           : 0.29.28
pytest           : 7.1.1
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : 3.0.3
lxml.etree       : None
html5lib         : None
pymysql          : 1.0.2
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : 0.8.9
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46873/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46873/timeline,
8,https://api.github.com/repos/pandas-dev/pandas/issues/46870,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46870/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46870/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46870/events,https://github.com/pandas-dev/pandas/issues/46870,1214958040,I_kwDOAA0YD85IasnY,46870,BUG: DataFrame.select_dtypes(include='number') includes BooleanDtype columns,"{'login': 'macks22', 'id': 3409997, 'node_id': 'MDQ6VXNlcjM0MDk5OTc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3409997?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/macks22', 'html_url': 'https://github.com/macks22', 'followers_url': 'https://api.github.com/users/macks22/followers', 'following_url': 'https://api.github.com/users/macks22/following{/other_user}', 'gists_url': 'https://api.github.com/users/macks22/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/macks22/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/macks22/subscriptions', 'organizations_url': 'https://api.github.com/users/macks22/orgs', 'repos_url': 'https://api.github.com/users/macks22/repos', 'events_url': 'https://api.github.com/users/macks22/events{/privacy}', 'received_events_url': 'https://api.github.com/users/macks22/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-25T19:37:48Z,2022-04-25T19:37:48Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd

df = pd.DataFrame({
    'a': [1, 2, 3],
    'b': pd.Series([True, False, True], dtype=pd.BooleanDtype()),
})
print(df.select_dtypes(include='number').columns)
# Output: Index(['a', 'b'], dtype='object')
```


### Issue Description

The `DataFrame.select_dtypes` method includes columns with `dtype` of `BooleanDtype` when `include='number'` is given as a kwarg. This is different than the behavior for columns with `dtype` of `bool` and seems like a bug.

### Expected Behavior

The code above should output: `Index(['a'], dtype='object')`


### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.12.final.0
python-bits      : 64
OS               : Darwin
OS-release       : 20.6.0
Version          : Darwin Kernel Version 20.6.0: Tue Feb 22 21:10:41 PST 2022; root:xnu-7195.141.26~1/RELEASE_X86_64
machine          : x86_64
processor        : i386
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.21.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.4
setuptools       : 59.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : 8.2.0
pandas_datareader: None
bs4              : None
bottleneck       : 1.3.4
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46870/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46870/timeline,
9,https://api.github.com/repos/pandas-dev/pandas/issues/46869,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46869/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46869/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46869/events,https://github.com/pandas-dev/pandas/issues/46869,1214926495,I_kwDOAA0YD85Iak6f,46869,BUG: SettingWithCopyWarning,"{'login': 'iliya-malecki', 'id': 53195438, 'node_id': 'MDQ6VXNlcjUzMTk1NDM4', 'avatar_url': 'https://avatars.githubusercontent.com/u/53195438?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/iliya-malecki', 'html_url': 'https://github.com/iliya-malecki', 'followers_url': 'https://api.github.com/users/iliya-malecki/followers', 'following_url': 'https://api.github.com/users/iliya-malecki/following{/other_user}', 'gists_url': 'https://api.github.com/users/iliya-malecki/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/iliya-malecki/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/iliya-malecki/subscriptions', 'organizations_url': 'https://api.github.com/users/iliya-malecki/orgs', 'repos_url': 'https://api.github.com/users/iliya-malecki/repos', 'events_url': 'https://api.github.com/users/iliya-malecki/events{/privacy}', 'received_events_url': 'https://api.github.com/users/iliya-malecki/received_events', 'type': 'User', 'site_admin': False}","[{'id': 34444536, 'node_id': 'MDU6TGFiZWwzNDQ0NDUzNg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Usage%20Question', 'name': 'Usage Question', 'color': '0052cc', 'default': False, 'description': None}, {'id': 1628184320, 'node_id': 'MDU6TGFiZWwxNjI4MTg0MzIw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Warnings', 'name': 'Warnings', 'color': 'f2f074', 'default': False, 'description': 'Warnings that appear or should be added to pandas'}, {'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,2,2022-04-25T19:09:44Z,2022-04-26T12:42:13Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  available_data['loading'] = 1
```


### Issue Description

Sorry but for the life of me i cant create a reproducible example. It is just a dataframe that was created using `maindf.query('some_time > @todays_datetime')`
available_data.values.base is maindf.values.base # False

### Expected Behavior

not have the warning

### Installed Versions

<details>


INSTALLED VERSIONS
------------------
commit           : 5f648bf1706dd75a9ca0d29f26eadfbb595fe52b
python           : 3.8.5.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-1051-azure
Version          : #53~18.04.1-Ubuntu SMP Fri Jun 18 22:32:58 UTC 2021
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.2
numpy            : 1.21.2
pytz             : 2021.1
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 52.0.0.post20210125
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.1
IPython          : 7.27.0
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : 3.4.3
numexpr          : None
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 3.0.0
pyxlsb           : None
s3fs             : None
scipy            : 1.7.1
sqlalchemy       : 1.4.35
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46869/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46869/timeline,
10,https://api.github.com/repos/pandas-dev/pandas/issues/46868,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46868/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46868/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46868/events,https://github.com/pandas-dev/pandas/issues/46868,1214886558,I_kwDOAA0YD85IabKe,46868,ENH: Dataframe constructor and DataFrame.from_records shoudl allow specifying column dtypes,"{'login': 'jlumpe', 'id': 7455396, 'node_id': 'MDQ6VXNlcjc0NTUzOTY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/7455396?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jlumpe', 'html_url': 'https://github.com/jlumpe', 'followers_url': 'https://api.github.com/users/jlumpe/followers', 'following_url': 'https://api.github.com/users/jlumpe/following{/other_user}', 'gists_url': 'https://api.github.com/users/jlumpe/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jlumpe/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jlumpe/subscriptions', 'organizations_url': 'https://api.github.com/users/jlumpe/orgs', 'repos_url': 'https://api.github.com/users/jlumpe/repos', 'events_url': 'https://api.github.com/users/jlumpe/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jlumpe/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-25T18:31:42Z,2022-04-25T18:31:42Z,,NONE,,,,"#### Is your feature request related to a problem?

When creating a `DataFrame` from a list of row tuples using either the constructor or `DataFrame.from_rows()`, I often run into issues where the column data type is not inferred correctly. In my specific case I have a mix of `int`s and `None`s and would like to have an `object` dtype, but pandas wants to convert to `float`.

#### Describe the solution you'd like

`read_csv()` has a `dtype` argument that allows setting individual column data types, I think these two methods should have something similar. The constructor does already have a `dtype` argument but it accepts only a single value, and tabular data is very frequently not of a uniform data type. Because the `columns` argument is optional it should probably accept a list/sequence of `dtype`s instead of just a dict keyed by column names as in `read_csv()`.

#### API breaking implications

None, this would add a new optional argument to `DataFrame.from_records()` and expand the allowed values of the `dtype` argument to the constructor without changing the interpretation of currently accepted values.

#### Describe alternatives you've considered

```
df['A'] = df['A'].astype(dtype)
```

may work in a lot of cases, but mine requires an ugly list comprehension to undo the float conversion. Being able to manually specify the column data types seems like a no-brainer.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46868/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46868/timeline,
11,https://api.github.com/repos/pandas-dev/pandas/issues/46867,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46867/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46867/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46867/events,https://github.com/pandas-dev/pandas/issues/46867,1214580563,I_kwDOAA0YD85IZQdT,46867,BUG: groupby.transform with execution engine numba does not work in multiindex case since 1.3,"{'login': 'derHeinzer', 'id': 43210452, 'node_id': 'MDQ6VXNlcjQzMjEwNDUy', 'avatar_url': 'https://avatars.githubusercontent.com/u/43210452?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/derHeinzer', 'html_url': 'https://github.com/derHeinzer', 'followers_url': 'https://api.github.com/users/derHeinzer/followers', 'following_url': 'https://api.github.com/users/derHeinzer/following{/other_user}', 'gists_url': 'https://api.github.com/users/derHeinzer/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/derHeinzer/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/derHeinzer/subscriptions', 'organizations_url': 'https://api.github.com/users/derHeinzer/orgs', 'repos_url': 'https://api.github.com/users/derHeinzer/repos', 'events_url': 'https://api.github.com/users/derHeinzer/events{/privacy}', 'received_events_url': 'https://api.github.com/users/derHeinzer/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-25T14:16:16Z,2022-04-25T14:16:16Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd


df = pd.DataFrame([{'A': 1, 'B': 2, 'C': 3}]).set_index([""A"", ""B""])


def numba_func(values, index):
    return 1


res = df.groupby('A').transform(
    numba_func, engine=""numba""
)
```


### Issue Description

Traceback (most recent call last):
  File ""/home/ninja/workspace/lumen_psf/python/psf/script/dev_tst.py"", line 11, in <module>
    res = df.groupby('A').transform(
  File ""/home/ninja/miniconda3/envs/py39pandas13/lib/python3.9/site-packages/pandas/core/groupby/generic.py"", line 1357, in transform
    return self._transform(
  File ""/home/ninja/miniconda3/envs/py39pandas13/lib/python3.9/site-packages/pandas/core/groupby/groupby.py"", line 1430, in _transform
    result = self._transform_with_numba(
  File ""/home/ninja/miniconda3/envs/py39pandas13/lib/python3.9/site-packages/pandas/core/groupby/groupby.py"", line 1187, in _transform_with_numba
    result = numba_transform_func(
  File ""/home/ninja/miniconda3/envs/py39pandas13/lib/python3.9/site-packages/numba/core/dispatcher.py"", line 468, in _compile_for_args
    error_rewrite(e, 'typing')
  File ""/home/ninja/miniconda3/envs/py39pandas13/lib/python3.9/site-packages/numba/core/dispatcher.py"", line 409, in error_rewrite
    raise e.with_traceback(None)
numba.core.errors.TypingError: Failed in nopython mode pipeline (step: nopython frontend)
non-precise type array(pyobject, 1d, C)
During: typing of argument at /home/ninja/miniconda3/envs/py39pandas13/lib/python3.9/site-packages/pandas/core/groupby/numba_.py (167)

File ""../../../../../miniconda3/envs/py39pandas13/lib/python3.9/site-packages/pandas/core/groupby/numba_.py"", line 167:
    def group_transform(
        <source elided>
    ) -> np.ndarray:
        result = np.empty((len(values), num_columns))
        ^



### Expected Behavior

Up to pandas version 1.2 this worked like a charm. Apparently the redesign of the grouping did not respect to multi-index cases when using calculation engine numba.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 66e3805b8cabe977f40c05259cc3fcf7ead5687d
python           : 3.9.12.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-40-generic
Version          : #45~20.04.1-Ubuntu SMP Mon Apr 4 09:38:31 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.3.5
numpy            : 1.21.6
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 59.8.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
fsspec           : None
fastparquet      : None
gcsfs            : None
matplotlib       : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyxlsb           : None
s3fs             : None
scipy            : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
numba            : 0.55.1


</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46867/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46867/timeline,
12,https://api.github.com/repos/pandas-dev/pandas/issues/46865,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46865/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46865/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46865/events,https://github.com/pandas-dev/pandas/issues/46865,1214372321,I_kwDOAA0YD85IYdnh,46865,STYLE replace flake8-rst with something maintained,"{'login': 'MarcoGorelli', 'id': 33491632, 'node_id': 'MDQ6VXNlcjMzNDkxNjMy', 'avatar_url': 'https://avatars.githubusercontent.com/u/33491632?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/MarcoGorelli', 'html_url': 'https://github.com/MarcoGorelli', 'followers_url': 'https://api.github.com/users/MarcoGorelli/followers', 'following_url': 'https://api.github.com/users/MarcoGorelli/following{/other_user}', 'gists_url': 'https://api.github.com/users/MarcoGorelli/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/MarcoGorelli/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/MarcoGorelli/subscriptions', 'organizations_url': 'https://api.github.com/users/MarcoGorelli/orgs', 'repos_url': 'https://api.github.com/users/MarcoGorelli/repos', 'events_url': 'https://api.github.com/users/MarcoGorelli/events{/privacy}', 'received_events_url': 'https://api.github.com/users/MarcoGorelli/received_events', 'type': 'User', 'site_admin': False}","[{'id': 106935113, 'node_id': 'MDU6TGFiZWwxMDY5MzUxMTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Code%20Style', 'name': 'Code Style', 'color': 'eb6420', 'default': False, 'description': 'Code style, linting, code_checks'}, {'id': 717120670, 'node_id': 'MDU6TGFiZWw3MTcxMjA2NzA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/good%20first%20issue', 'name': 'good first issue', 'color': '0e8a16', 'default': True, 'description': None}]",open,False,,[],,0,2022-04-25T11:31:53Z,2022-04-25T11:31:53Z,,MEMBER,,,,"Currently, we use flake8-rst for running flake8 in code snippets in rst files:

https://github.com/pandas-dev/pandas/blob/2e56a838cf5ed3058df16c11e5ebae862520bab7/.pre-commit-config.yaml#L95-L102

However, flake8-rst isn't maintained, and is currently run in its own environment with a different flake8 version because of incompatibilities with flake8 v4

Task here is:
- search around to see if there's a maintained tool which does the same thing (runs flake8 on code snippets in rst files)
- try using that instead, fixup any new errors which may result from running it via `pre-commit` on all files
- make a PR","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46865/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46865/timeline,
13,https://api.github.com/repos/pandas-dev/pandas/issues/46864,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46864/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46864/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46864/events,https://github.com/pandas-dev/pandas/issues/46864,1214319136,I_kwDOAA0YD85IYQog,46864,BUG: duplicated() returns different results on consecutive runs!,"{'login': 'emsi', 'id': 433383, 'node_id': 'MDQ6VXNlcjQzMzM4Mw==', 'avatar_url': 'https://avatars.githubusercontent.com/u/433383?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/emsi', 'html_url': 'https://github.com/emsi', 'followers_url': 'https://api.github.com/users/emsi/followers', 'following_url': 'https://api.github.com/users/emsi/following{/other_user}', 'gists_url': 'https://api.github.com/users/emsi/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/emsi/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/emsi/subscriptions', 'organizations_url': 'https://api.github.com/users/emsi/orgs', 'repos_url': 'https://api.github.com/users/emsi/repos', 'events_url': 'https://api.github.com/users/emsi/events{/privacy}', 'received_events_url': 'https://api.github.com/users/emsi/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}, {'id': 1633019538, 'node_id': 'MDU6TGFiZWwxNjMzMDE5NTM4', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/duplicated', 'name': 'duplicated', 'color': 'fc6feb', 'default': False, 'description': 'duplicated, drop_duplicates'}]",open,False,,[],,3,2022-04-25T10:47:26Z,2022-04-26T16:39:42Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
# Unfortunately I have to provide a downloadable dataframe example (51MB).
# I guess either the size or encoding of the data contributes to the problem.
# Dataset can be downloaded like this:
# !wget https://github.com/emsi/artifacts/raw/master/sources.jl

import joblib as jl

df = jl.load(""sources.jl"")

# multiple calls to duplicate() yield different results!
pd.Series([len(df[df.duplicated()]) for _ in range(500)]).describe()
```


### Issue Description

When I call `duplicated()` on a given dataframe it returns different results like it has some stochasticity built in. The number of found duplicates differs. Sometimes it's 5507 sometimes its 5509. I even replicated this on another computer as I suspected some CPU/RAM problem.

```
>>> pd.Series([len(df[df.duplicated()]) for _ in range(500)]).describe()

count     500.000000
mean     5507.884000
std         0.957276
min      5507.000000
25%      5507.000000
50%      5507.000000
75%      5509.000000
max      5509.000000
dtype: float64
```


### Expected Behavior

I'd expect `duplicated()` to produce reproducible results. :)

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.0.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.0-100-generic
Version          : #113-Ubuntu SMP Thu Feb 3 18:43:29 UTC 2022
machine          : x86_64
processor        : 
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.19.2
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 20.2.3
setuptools       : 50.3.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : 4.7.1
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 8.0.1
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : 2022.01.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.1
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : None
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : None
zstandard        : None



</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46864/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46864/timeline,
14,https://api.github.com/repos/pandas-dev/pandas/issues/46863,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46863/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46863/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46863/events,https://github.com/pandas-dev/pandas/issues/46863,1214306290,I_kwDOAA0YD85IYNfy,46863,BUG: `to_parquet` failing for integer-like string values in categorical column,"{'login': 'RabeezRiaz', 'id': 93147076, 'node_id': 'U_kgDOBY1PxA', 'avatar_url': 'https://avatars.githubusercontent.com/u/93147076?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RabeezRiaz', 'html_url': 'https://github.com/RabeezRiaz', 'followers_url': 'https://api.github.com/users/RabeezRiaz/followers', 'following_url': 'https://api.github.com/users/RabeezRiaz/following{/other_user}', 'gists_url': 'https://api.github.com/users/RabeezRiaz/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RabeezRiaz/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RabeezRiaz/subscriptions', 'organizations_url': 'https://api.github.com/users/RabeezRiaz/orgs', 'repos_url': 'https://api.github.com/users/RabeezRiaz/repos', 'events_url': 'https://api.github.com/users/RabeezRiaz/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RabeezRiaz/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 78527356, 'node_id': 'MDU6TGFiZWw3ODUyNzM1Ng==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Categorical', 'name': 'Categorical', 'color': 'e11d21', 'default': False, 'description': 'Categorical Data Type'}, {'id': 307649777, 'node_id': 'MDU6TGFiZWwzMDc2NDk3Nzc=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Info', 'name': 'Needs Info', 'color': '207de5', 'default': False, 'description': 'Clarification about behavior needed to assess issue'}, {'id': 685114413, 'node_id': 'MDU6TGFiZWw2ODUxMTQ0MTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/IO%20Parquet', 'name': 'IO Parquet', 'color': '5319e7', 'default': False, 'description': 'parquet, feather'}]",open,False,,[],,4,2022-04-25T10:35:51Z,2022-04-26T14:49:41Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [ ] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
# Happy to provide a reproducible example if someone can guide on *what* the example should be since the issue only seems to happen on my full series of raw data
```


### Issue Description

I receive the following exception when trying `df.to_parquet()`:
```
ArrowInvalid: (""Could not convert <pyarrow.StringScalar: '50015202101011004687846'> with type pyarrow.lib.StringScalar: did not recognize Python value type when inferring an Arrow data type"", 'Conversion failed for column Ticket ID with type category')
```

This is the problematic column:
![image](https://user-images.githubusercontent.com/93147076/165072052-34c4f836-b013-4142-a38e-2059ac82332c.png)

Same exception persists if I manually try to convert that whole column using `pa.array()`:
```
ArrowInvalid: Could not convert <pyarrow.StringScalar: '50015202101011004687846'> with type pyarrow.lib.StringScalar: did not recognize Python value type when inferring an Arrow data type
```

Trying the same with a length 1 series for the value in the exception results in exactly the same exception 
```
pa.array(df_full.loc[[15247763],""Ticket ID""])
```

but the conversion passes successfully if I remove unused categories through pandas beforehand:
```
pa.array(df_full.loc[[15247763],""Ticket ID""].cat.remove_unused_categories())
```

### Expected Behavior

I can't understand what type arrow is trying to infer here, or why this expected type changes when I remove the categories for which their is no error. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.9.7.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.13.0-1021-aws
Version          : #23~20.04.2-Ubuntu SMP Thu Mar 31 11:36:15 UTC 2022
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : en_US.UTF-8
LANG             : en_US.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.19.5
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.3.1
setuptools       : 58.0.4
Cython           : None
pytest           : 7.1.2
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : 3.0.3
IPython          : 7.32.0
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : 
fastparquet      : 0.8.1
fsspec           : 2021.10.1
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.3.4
numba            : None
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.8.0
snappy           : None
sqlalchemy       : 1.4.29
tables           : 3.7.0
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46863/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46863/timeline,
15,https://api.github.com/repos/pandas-dev/pandas/issues/46862,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46862/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46862/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46862/events,https://github.com/pandas-dev/pandas/pull/46862,1213840582,PR_kwDOAA0YD842sUKc,46862,BUG: Raise error when expr does not evaluate to bool in df.query ,"{'login': 'NumberPiOso', 'id': 46936498, 'node_id': 'MDQ6VXNlcjQ2OTM2NDk4', 'avatar_url': 'https://avatars.githubusercontent.com/u/46936498?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/NumberPiOso', 'html_url': 'https://github.com/NumberPiOso', 'followers_url': 'https://api.github.com/users/NumberPiOso/followers', 'following_url': 'https://api.github.com/users/NumberPiOso/following{/other_user}', 'gists_url': 'https://api.github.com/users/NumberPiOso/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/NumberPiOso/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/NumberPiOso/subscriptions', 'organizations_url': 'https://api.github.com/users/NumberPiOso/orgs', 'repos_url': 'https://api.github.com/users/NumberPiOso/repos', 'events_url': 'https://api.github.com/users/NumberPiOso/events{/privacy}', 'received_events_url': 'https://api.github.com/users/NumberPiOso/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1631985267, 'node_id': 'MDU6TGFiZWwxNjMxOTg1MjY3', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/expressions', 'name': 'expressions', 'color': 'f3afff', 'default': False, 'description': 'pd.eval, query'}]",open,False,,[],,1,2022-04-25T01:34:28Z,2022-04-26T23:24:14Z,,CONTRIBUTOR,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46862', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46862', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46862.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46862.patch', 'merged_at': None}","- [X] closes  #8560
- [X] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [X] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [X] Added an entry in the latest `doc/source/whatsnew/v1.5.0.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46862/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46862/timeline,
16,https://api.github.com/repos/pandas-dev/pandas/issues/46860,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46860/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46860/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46860/events,https://github.com/pandas-dev/pandas/pull/46860,1213714027,PR_kwDOAA0YD842r6-w,46860,BUG: Series.map is ignoring the na_action keyword,"{'login': 'stanleycai95', 'id': 46463107, 'node_id': 'MDQ6VXNlcjQ2NDYzMTA3', 'avatar_url': 'https://avatars.githubusercontent.com/u/46463107?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/stanleycai95', 'html_url': 'https://github.com/stanleycai95', 'followers_url': 'https://api.github.com/users/stanleycai95/followers', 'following_url': 'https://api.github.com/users/stanleycai95/following{/other_user}', 'gists_url': 'https://api.github.com/users/stanleycai95/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/stanleycai95/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/stanleycai95/subscriptions', 'organizations_url': 'https://api.github.com/users/stanleycai95/orgs', 'repos_url': 'https://api.github.com/users/stanleycai95/repos', 'events_url': 'https://api.github.com/users/stanleycai95/events{/privacy}', 'received_events_url': 'https://api.github.com/users/stanleycai95/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyMzQy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data', 'name': 'Missing-data', 'color': 'd7e102', 'default': False, 'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 78, 'closed_issues': 690, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-04-26T22:10:05Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",2,2022-04-24T17:22:11Z,2022-04-26T20:03:24Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46860', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46860', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46860.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46860.patch', 'merged_at': None}","- [x] closes #46588 
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [x] Added an entry in the latest doc/source/whatsnew/v1.5.0.rst file if fixing a bug or adding a new feature.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46860/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46860/timeline,
17,https://api.github.com/repos/pandas-dev/pandas/issues/46859,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46859/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46859/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46859/events,https://github.com/pandas-dev/pandas/issues/46859,1213672764,I_kwDOAA0YD85IVy08,46859,ENH: Support multiple instances of styler object,"{'login': 'bhishanpdl', 'id': 13811914, 'node_id': 'MDQ6VXNlcjEzODExOTE0', 'avatar_url': 'https://avatars.githubusercontent.com/u/13811914?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/bhishanpdl', 'html_url': 'https://github.com/bhishanpdl', 'followers_url': 'https://api.github.com/users/bhishanpdl/followers', 'following_url': 'https://api.github.com/users/bhishanpdl/following{/other_user}', 'gists_url': 'https://api.github.com/users/bhishanpdl/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/bhishanpdl/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/bhishanpdl/subscriptions', 'organizations_url': 'https://api.github.com/users/bhishanpdl/orgs', 'repos_url': 'https://api.github.com/users/bhishanpdl/repos', 'events_url': 'https://api.github.com/users/bhishanpdl/events{/privacy}', 'received_events_url': 'https://api.github.com/users/bhishanpdl/received_events', 'type': 'User', 'site_admin': False}","[{'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEwMTExOA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting', 'name': 'Output-Formatting', 'color': 'ededed', 'default': False, 'description': '__repr__ of pandas objects, to_string'}, {'id': 1728592794, 'node_id': 'MDU6TGFiZWwxNzI4NTkyNzk0', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Styler', 'name': 'Styler', 'color': '006b75', 'default': False, 'description': 'conditional formatting using DataFrame.style'}, {'id': 2365504893, 'node_id': 'MDU6TGFiZWwyMzY1NTA0ODkz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Closing%20Candidate', 'name': 'Closing Candidate', 'color': 'be21f2', 'default': False, 'description': 'May be closeable, needs more eyeballs'}]",open,False,,[],,1,2022-04-24T14:38:42Z,2022-04-25T05:29:45Z,,NONE,,,,"# Feature request
```python
import numpy as np
import pandas as pd

np.random.seed(0)
pd.options.display.float_format = None


df = pd.DataFrame({'a': np.random.rand(1,10)[0],
                  'b': np.random.rand(1,10)[0]})

df_style = df.style.format({'a':""{:.2f}""})
df_style = df_style.format({'b':""{:.2f}""})
df_style # only column b is formatted
```

# What works
```python
df_style = df.style.format({'a':""{:.2f}"",'b':""{:.2f}""})
```

# What is requested
```python
df_style = df.style.format({'a':""{:.2f}""})
df_style = df_style.format({'b':""{:.2f}""})
df_style # only column b is formatted
```

Sometimes we have long chain of methods in styler, we may want to additional format down the line for different columns. This might be helpful.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46859/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46859/timeline,
18,https://api.github.com/repos/pandas-dev/pandas/issues/46858,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46858/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46858/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46858/events,https://github.com/pandas-dev/pandas/issues/46858,1213516370,I_kwDOAA0YD85IVMpS,46858,convert_dtypes need support convert string with nan to int .,"{'login': 'eromoe', 'id': 3938751, 'node_id': 'MDQ6VXNlcjM5Mzg3NTE=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3938751?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/eromoe', 'html_url': 'https://github.com/eromoe', 'followers_url': 'https://api.github.com/users/eromoe/followers', 'following_url': 'https://api.github.com/users/eromoe/following{/other_user}', 'gists_url': 'https://api.github.com/users/eromoe/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/eromoe/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/eromoe/subscriptions', 'organizations_url': 'https://api.github.com/users/eromoe/orgs', 'repos_url': 'https://api.github.com/users/eromoe/repos', 'events_url': 'https://api.github.com/users/eromoe/events{/privacy}', 'received_events_url': 'https://api.github.com/users/eromoe/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76812, 'node_id': 'MDU6TGFiZWw3NjgxMg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Enhancement', 'name': 'Enhancement', 'color': '4E9A06', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,4,2022-04-24T03:28:47Z,2022-04-26T21:59:34Z,,NONE,,,,"#### Is your feature request related to a problem?

convert_dtypes need support convert string with nan to int

#### Describe the solution you'd like

Now, pandas doesn't consider string with nan case as numerical variable .
```
pd.Series(['1', '2', '3', np.nan]).convert_dtypes().dtype
```
got
```
string[python]
```

#### Describe alternatives you've considered




```
pd.Series(['1', '2', '3', np.nan]).convert_dtypes().dtype
```

should like `pd.Series(['1', '2', '3', np.nan]).astype('Int16').dtype`
```
Int16Dtype()
```

","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46858/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46858/timeline,
19,https://api.github.com/repos/pandas-dev/pandas/issues/46856,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46856/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46856/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46856/events,https://github.com/pandas-dev/pandas/issues/46856,1213495503,I_kwDOAA0YD85IVHjP,46856,TST: Fix xfail for git component of `pd.show_version` tests on 32 bit builds,"{'login': 'mroeschke', 'id': 10647082, 'node_id': 'MDQ6VXNlcjEwNjQ3MDgy', 'avatar_url': 'https://avatars.githubusercontent.com/u/10647082?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/mroeschke', 'html_url': 'https://github.com/mroeschke', 'followers_url': 'https://api.github.com/users/mroeschke/followers', 'following_url': 'https://api.github.com/users/mroeschke/following{/other_user}', 'gists_url': 'https://api.github.com/users/mroeschke/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/mroeschke/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/mroeschke/subscriptions', 'organizations_url': 'https://api.github.com/users/mroeschke/orgs', 'repos_url': 'https://api.github.com/users/mroeschke/repos', 'events_url': 'https://api.github.com/users/mroeschke/events{/privacy}', 'received_events_url': 'https://api.github.com/users/mroeschke/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 563047854, 'node_id': 'MDU6TGFiZWw1NjMwNDc4NTQ=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/32bit', 'name': '32bit', 'color': '0e8a16', 'default': False, 'description': '32-bit systems'}]",open,False,,[],,2,2022-04-24T01:21:03Z,2022-04-26T01:24:15Z,,MEMBER,,,,Two tests were xfailed in this PR that suddenly failed. https://github.com/pandas-dev/pandas/pull/46842,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46856/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46856/timeline,
20,https://api.github.com/repos/pandas-dev/pandas/issues/46854,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46854/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46854/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46854/events,https://github.com/pandas-dev/pandas/pull/46854,1213471906,PR_kwDOAA0YD842rQtl,46854,Add more overflow tests for timedelta64 operations,"{'login': 'patrickmckenna', 'id': 3589536, 'node_id': 'MDQ6VXNlcjM1ODk1MzY=', 'avatar_url': 'https://avatars.githubusercontent.com/u/3589536?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/patrickmckenna', 'html_url': 'https://github.com/patrickmckenna', 'followers_url': 'https://api.github.com/users/patrickmckenna/followers', 'following_url': 'https://api.github.com/users/patrickmckenna/following{/other_user}', 'gists_url': 'https://api.github.com/users/patrickmckenna/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/patrickmckenna/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/patrickmckenna/subscriptions', 'organizations_url': 'https://api.github.com/users/patrickmckenna/orgs', 'repos_url': 'https://api.github.com/users/patrickmckenna/repos', 'events_url': 'https://api.github.com/users/patrickmckenna/events{/privacy}', 'received_events_url': 'https://api.github.com/users/patrickmckenna/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127685, 'node_id': 'MDU6TGFiZWwxMjc2ODU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Testing', 'name': 'Testing', 'color': 'C4A000', 'default': False, 'description': 'pandas testing functions or related to the test suite'}, {'id': 49597148, 'node_id': 'MDU6TGFiZWw0OTU5NzE0OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timedelta', 'name': 'Timedelta', 'color': '5319e7', 'default': False, 'description': 'Timedelta data type'}]",open,False,,[],,2,2022-04-23T22:50:39Z,2022-04-26T18:40:41Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46854', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46854', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46854.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46854.patch', 'merged_at': None}","- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [x] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [x] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.

---

This PR adds more specific tests, to verify the current, sometimes inconsistent behavior. Much of it has been reported/discussed in previous threads, and some appears to reflect intentional tradeoffs, e.g. allowing rounding error to avoid overflows. Other behavior seems likely unintentional:

- Inconsistent usage of `ValueError` and `OverflowError`
- Spurious `OverflowError`s for 1-element `Series` w/ valid values

Since this is my first time poking around pandas/numpy internals, it seemed best to make sure the right tests are in the right places before attempting any fixes.



### Open Questions
- What exception should be raised if `Series.sum()` would yield an invalid `Timedelta`: `ValueError`, `OutOfBoundsTimedelta`, something else? (I can rewrite the tests to mark those cases that currently raise the ""wrong"" exception as `xfail` for now.)
- Is silently introducing rounding error considered ok, or should a warning be emitted?
- Is this the right spot for these tests? AFAICT, a lot of this behavior is determined by `pandas.core.nanops`, particularly special-casing of `timedelta64` in `nansum()`: https://github.com/pandas-dev/pandas/blob/4cf8d55b1549be756857d82480afec7072028a73/pandas/core/nanops.py#L618-L621 My assumption was that tests against the public API would be preferred, but please LMK if that's not the case.



### Prior Art
- https://github.com/pandas-dev/pandas/issues/43178
- https://github.com/pandas-dev/pandas/issues/9442
- https://github.com/pandas-dev/pandas/pull/10926","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46854/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46854/timeline,
21,https://api.github.com/repos/pandas-dev/pandas/issues/46852,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46852/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46852/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46852/events,https://github.com/pandas-dev/pandas/issues/46852,1213455551,I_kwDOAA0YD85IU9y_,46852,DEPR: numeric_only default on DataFrame ops,"{'login': 'rhshadrach', 'id': 45562402, 'node_id': 'MDQ6VXNlcjQ1NTYyNDAy', 'avatar_url': 'https://avatars.githubusercontent.com/u/45562402?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/rhshadrach', 'html_url': 'https://github.com/rhshadrach', 'followers_url': 'https://api.github.com/users/rhshadrach/followers', 'following_url': 'https://api.github.com/users/rhshadrach/following{/other_user}', 'gists_url': 'https://api.github.com/users/rhshadrach/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/rhshadrach/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/rhshadrach/subscriptions', 'organizations_url': 'https://api.github.com/users/rhshadrach/orgs', 'repos_url': 'https://api.github.com/users/rhshadrach/repos', 'events_url': 'https://api.github.com/users/rhshadrach/events{/privacy}', 'received_events_url': 'https://api.github.com/users/rhshadrach/received_events', 'type': 'User', 'site_admin': False}","[{'id': 87485152, 'node_id': 'MDU6TGFiZWw4NzQ4NTE1Mg==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Deprecate', 'name': 'Deprecate', 'color': '5319e7', 'default': False, 'description': 'Functionality to remove in pandas'}, {'id': 1741841389, 'node_id': 'MDU6TGFiZWwxNzQxODQxMzg5', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/API%20-%20Consistency', 'name': 'API - Consistency', 'color': 'b60205', 'default': False, 'description': 'Internal Consistency of API/Behavior'}, {'id': 2365504383, 'node_id': 'MDU6TGFiZWwyMzY1NTA0Mzgz', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reduction%20Operations', 'name': 'Reduction Operations', 'color': '547c03', 'default': False, 'description': 'sum, mean, min, max, etc.'}, {'id': 2365523662, 'node_id': 'MDU6TGFiZWwyMzY1NTIzNjYy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Nuisance%20Columns', 'name': 'Nuisance Columns', 'color': '120491', 'default': False, 'description': 'Identifying/Dropping nuisance columns in reductions, groupby.add, DataFrame.apply'}]",open,False,,[],,0,2022-04-23T21:10:42Z,2022-04-23T22:06:55Z,,MEMBER,,,,"In parallel with #46072 and part of #46560, numeric_only should default to False for all DataFrame ops in 2.0","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46852/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46852/timeline,
22,https://api.github.com/repos/pandas-dev/pandas/issues/46851,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46851/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46851/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46851/events,https://github.com/pandas-dev/pandas/issues/46851,1213296029,I_kwDOAA0YD85IUW2d,46851,BUG: strftime can give incorrect answers,"{'login': 'phil20686', 'id': 6398777, 'node_id': 'MDQ6VXNlcjYzOTg3Nzc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/6398777?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/phil20686', 'html_url': 'https://github.com/phil20686', 'followers_url': 'https://api.github.com/users/phil20686/followers', 'following_url': 'https://api.github.com/users/phil20686/following{/other_user}', 'gists_url': 'https://api.github.com/users/phil20686/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/phil20686/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/phil20686/subscriptions', 'organizations_url': 'https://api.github.com/users/phil20686/orgs', 'repos_url': 'https://api.github.com/users/phil20686/repos', 'events_url': 'https://api.github.com/users/phil20686/events{/privacy}', 'received_events_url': 'https://api.github.com/users/phil20686/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-23T13:09:18Z,2022-04-23T13:09:18Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
t1 = pd.Timestamp(year=2000,  month=12, day=25, nanosecond=123456)
t1.strftime(%S.%f) # gives ""00.000000""
t2 = pd.Timestamp(year=2000,  month=12, day=25, microsecond=123, nanosecond=456)
t2.strftime(%S.%f) # gives ""00.000123""
t1 == t2 # correctly yields true
```


### Issue Description

It is valid to enter a number of nanoseconds that is greater than 1000, but the constructor does not convert this to microseconds, so when strftime is called it seems to take only the value of the microsecond property. 

### Expected Behavior

It is expected that t1 and t2 should always give the same strftime in all cases. Note that microsecond errors if given a number over 999999 and I think the behaviour of erroring when given a nanosecond over 999 would be fine, and guarantee correct behaviour. 

### Installed Versions

For some reason this failed with an assertion error, but I do not think that is relevant to this report.","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46851/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46851/timeline,
23,https://api.github.com/repos/pandas-dev/pandas/issues/46850,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46850/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46850/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46850/events,https://github.com/pandas-dev/pandas/pull/46850,1213266629,PR_kwDOAA0YD842qvsX,46850,Update join docs for other param,"{'login': 'multimeric', 'id': 5019367, 'node_id': 'MDQ6VXNlcjUwMTkzNjc=', 'avatar_url': 'https://avatars.githubusercontent.com/u/5019367?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/multimeric', 'html_url': 'https://github.com/multimeric', 'followers_url': 'https://api.github.com/users/multimeric/followers', 'following_url': 'https://api.github.com/users/multimeric/following{/other_user}', 'gists_url': 'https://api.github.com/users/multimeric/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/multimeric/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/multimeric/subscriptions', 'organizations_url': 'https://api.github.com/users/multimeric/orgs', 'repos_url': 'https://api.github.com/users/multimeric/repos', 'events_url': 'https://api.github.com/users/multimeric/events{/privacy}', 'received_events_url': 'https://api.github.com/users/multimeric/received_events', 'type': 'User', 'site_admin': False}","[{'id': 134699, 'node_id': 'MDU6TGFiZWwxMzQ2OTk=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Docs', 'name': 'Docs', 'color': '3465A4', 'default': False, 'description': None}, {'id': 13098779, 'node_id': 'MDU6TGFiZWwxMzA5ODc3OQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Reshaping', 'name': 'Reshaping', 'color': '02d7e1', 'default': False, 'description': 'Concat, Merge/Join, Stack/Unstack, Explode'}]",open,False,,[],,1,2022-04-23T10:33:35Z,2022-04-25T21:14:56Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46850', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46850', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46850.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46850.patch', 'merged_at': None}","Currently the `DataFrame.join` docs imply that the type of `other` is `DataFrame | Series | list[DataFrame]`, but this is not correct, and `list[Series | DataFrame]` is a more appropriate type. 

The type signature and also the method description have been updated to amend this.

- [ ] closes #xxxx (Replace xxxx with the Github issue number)
- [ ] [Tests added and passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#writing-tests) if fixing a bug or adding a new feature
- [ ] All [code checks passed](https://pandas.pydata.org/pandas-docs/dev/development/contributing_codebase.html#pre-commit).
- [ ] Added an entry in the latest `doc/source/whatsnew/vX.X.X.rst` file if fixing a bug or adding a new feature.
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46850/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46850/timeline,
24,https://api.github.com/repos/pandas-dev/pandas/issues/46849,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46849/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46849/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46849/events,https://github.com/pandas-dev/pandas/issues/46849,1213204578,I_kwDOAA0YD85IUAhi,46849,BUG: not able to convert non-zero padded hour to timestamp. ,"{'login': 'RakeshJarupula', 'id': 53005533, 'node_id': 'MDQ6VXNlcjUzMDA1NTMz', 'avatar_url': 'https://avatars.githubusercontent.com/u/53005533?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/RakeshJarupula', 'html_url': 'https://github.com/RakeshJarupula', 'followers_url': 'https://api.github.com/users/RakeshJarupula/followers', 'following_url': 'https://api.github.com/users/RakeshJarupula/following{/other_user}', 'gists_url': 'https://api.github.com/users/RakeshJarupula/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/RakeshJarupula/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/RakeshJarupula/subscriptions', 'organizations_url': 'https://api.github.com/users/RakeshJarupula/orgs', 'repos_url': 'https://api.github.com/users/RakeshJarupula/repos', 'events_url': 'https://api.github.com/users/RakeshJarupula/events{/privacy}', 'received_events_url': 'https://api.github.com/users/RakeshJarupula/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-23T05:25:42Z,2022-04-23T05:26:32Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import pandas as pd
pd.to_datetime('2018-08-18 9', format='%Y-%m-%d %H', infer_datetime_format=True)
```


### Issue Description

Not able to convert the **non-zero padded Hour** and **zero padded date** to timestamp. 
`ParserError: Unknown string format: 2018-08-18 9`

Not having any issue converting:
`pd.to_datetime('2018-08-18 09', format='%Y-%m-%d %H', infer_datetime_format=True)`
OUTPUT: `Timestamp('2018-08-18 09:00:00')`

### Expected Behavior

I am expecting `Timestamp('2018-08-18 09:00:00')` with non-zero padded hour. 

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.8.13.final.0
python-bits      : 64
OS               : Windows
OS-release       : 10
Version          : 10.0.19043
machine          : AMD64
processor        : Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
byteorder        : little
LC_ALL           : None
LANG             : None
LOCALE           : English_India.1252

pandas           : 1.4.2
numpy            : 1.20.3
pytz             : 2021.3
dateutil         : 2.8.2
pip              : 21.2.2
setuptools       : 58.0.4
Cython           : 0.29.25
pytest           : 6.2.5
hypothesis       : None
sphinx           : 4.4.0
blosc            : None
feather          : None
xlsxwriter       : 3.0.2
lxml.etree       : 4.7.1
html5lib         : 1.1
pymysql          : None
psycopg2         : 2.9.1
jinja2           : 2.11.3
IPython          : 8.2.0
pandas_datareader: None
bs4              : 4.10.0
bottleneck       : 1.3.4
brotli           : 
fastparquet      : None
fsspec           : 2022.02.0
gcsfs            : None
markupsafe       : 2.0.1
matplotlib       : 3.5.0
numba            : 0.54.1
numexpr          : 2.8.1
odfpy            : None
openpyxl         : 3.0.9
pandas_gbq       : None
pyarrow          : 7.0.0
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : 1.7.3
snappy           : None
sqlalchemy       : 1.4.27
tables           : 3.6.1
tabulate         : None
xarray           : None
xlrd             : 2.0.1
xlwt             : 1.3.0
zstandard        : None

</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46849/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46849/timeline,
25,https://api.github.com/repos/pandas-dev/pandas/issues/46848,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46848/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46848/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46848/events,https://github.com/pandas-dev/pandas/issues/46848,1213107307,I_kwDOAA0YD85IToxr,46848,BUG: Segfault when printing dataframe,"{'login': 'hrenski', 'id': 53806545, 'node_id': 'MDQ6VXNlcjUzODA2NTQ1', 'avatar_url': 'https://avatars.githubusercontent.com/u/53806545?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/hrenski', 'html_url': 'https://github.com/hrenski', 'followers_url': 'https://api.github.com/users/hrenski/followers', 'following_url': 'https://api.github.com/users/hrenski/following{/other_user}', 'gists_url': 'https://api.github.com/users/hrenski/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/hrenski/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/hrenski/subscriptions', 'organizations_url': 'https://api.github.com/users/hrenski/orgs', 'repos_url': 'https://api.github.com/users/hrenski/repos', 'events_url': 'https://api.github.com/users/hrenski/events{/privacy}', 'received_events_url': 'https://api.github.com/users/hrenski/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 2822342, 'node_id': 'MDU6TGFiZWwyODIyMzQy', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Missing-data', 'name': 'Missing-data', 'color': 'd7e102', 'default': False, 'description': 'np.nan, pd.NaT, pd.NA, dropna, isnull, interpolate'}, {'id': 13101118, 'node_id': 'MDU6TGFiZWwxMzEwMTExOA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Output-Formatting', 'name': 'Output-Formatting', 'color': 'ededed', 'default': False, 'description': '__repr__ of pandas objects, to_string'}, {'id': 1121248195, 'node_id': 'MDU6TGFiZWwxMTIxMjQ4MTk1', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Segfault', 'name': 'Segfault', 'color': '36ede0', 'default': False, 'description': 'Non-Recoverable Error'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 988, 'closed_issues': 841, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-04-26T01:14:35Z', 'due_on': None, 'closed_at': None}",2,2022-04-23T02:11:36Z,2022-04-24T19:29:56Z,,NONE,,,,"### Pandas version checks

- [X] I have checked that this issue has not already been reported.

- [X] I have confirmed this bug exists on the [latest version](https://pandas.pydata.org/docs/whatsnew/index.html) of pandas.

- [X] I have confirmed this bug exists on the main branch of pandas.


### Reproducible Example

```python
import numpy as np
import pandas as pd

df = pd.DataFrame(np.empty((1, 33), dtype = object))

for col in df.columns:
    df[col] = np.empty_like(df[col])
    
print(df)
```


### Issue Description

I first wanted to put out a thank you to all those that work on keeping pandas going! All of your contributions have helped so many, and I appreciate it.

When running the example code, a segfault occurs at the last line: ```print(df)```. I'm sure this wouldn't be the recommended approach to doing this, but I wanted to give a minimal example showing the issues that I had come across. Also, note that replacing ```df[col] = np.empty_like(df[col])``` with ```df[col] = np.empty(len(df), dtype = df[col].dtype)``` prevents the issue from arising. But, based on the output of faulthandler (see below), I opted to submit it to the pandas team.

<details>
Fatal Python error: Segmentation fault

Current thread 0x00007fabaf0ba180 (most recent call first):
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/array_algos/take.py"", line 163 in _take_nd_ndarray
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/array_algos/take.py"", line 117 in take_nd
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/internals/blocks.py"", line 1137 in take_nd
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/internals/managers.py"", line 844 in _slice_take_blocks_ax0
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/generic.py"", line 3916 in _slice
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/indexing.py"", line 1533 in _get_slice_axis
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/indexing.py"", line 1497 in _getitem_axis
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/indexing.py"", line 827 in _getitem_tuple_same_dim
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/indexing.py"", line 1462 in _getitem_tuple
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/indexing.py"", line 961 in __getitem__
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/io/formats/format.py"", line 806 in _truncate_horizontally
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/io/formats/format.py"", line 790 in truncate
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/io/formats/string.py"", line 185 in _fit_strcols_to_terminal_width
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/io/formats/string.py"", line 49 in _get_string_representation
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/io/formats/string.py"", line 25 in to_string
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/io/formats/format.py"", line 1128 in to_string
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/frame.py"", line 1192 in to_string
  File ""/home/me/sml-env/lib/python3.10/site-packages/pandas/core/frame.py"", line 1011 in __repr__
  File ""/home/me/test.py"", line 13 in <module>

Extension modules: numpy.core._multiarray_umath, numpy.core._multiarray_tests, numpy.linalg._umath_linalg, numpy.fft._pocketfft_internal, numpy.random._common, numpy.random.bit_generator, numpy.random._bounded_integers, numpy.random._mt19937, numpy.random.mtrand, numpy.random._philox, numpy.random._pcg64, numpy.random._sfc64, numpy.random._generator, pandas._libs.tslibs.dtypes, pandas._libs.tslibs.base, pandas._libs.tslibs.np_datetime, pandas._libs.tslibs.nattype, pandas._libs.tslibs.timezones, pandas._libs.tslibs.ccalendar, pandas._libs.tslibs.tzconversion, pandas._libs.tslibs.strptime, pandas._libs.tslibs.fields, pandas._libs.tslibs.timedeltas, pandas._libs.tslibs.timestamps, pandas._libs.properties, pandas._libs.tslibs.offsets, pandas._libs.tslibs.parsing, pandas._libs.tslibs.conversion, pandas._libs.tslibs.period, pandas._libs.tslibs.vectorized, pandas._libs.ops_dispatch, pandas._libs.missing, pandas._libs.hashtable, pandas._libs.algos, pandas._libs.interval, pandas._libs.tslib, pandas._libs.lib, pandas._libs.hashing, pandas._libs.ops, pandas._libs.arrays, pandas._libs.index, pandas._libs.join, pandas._libs.sparse, pandas._libs.reduction, pandas._libs.indexing, pandas._libs.internals, pandas._libs.writers, pandas._libs.window.aggregations, pandas._libs.window.indexers, pandas._libs.reshape, pandas._libs.groupby, pandas._libs.testing, pandas._libs.parsers, pandas._libs.json (total: 54)

</details>



### Expected Behavior

I would expect the dataframe would be able to print after updating the columns.

### Installed Versions

<details>

INSTALLED VERSIONS
------------------
commit           : 4bfe3d07b4858144c219b9346329027024102ab6
python           : 3.10.4.final.0
python-bits      : 64
OS               : Linux
OS-release       : 5.4.72-microsoft-standard-WSL2
Version          : #1 SMP Wed Oct 28 23:40:43 UTC 2020
machine          : x86_64
processor        : x86_64
byteorder        : little
LC_ALL           : None
LANG             : C.UTF-8
LOCALE           : en_US.UTF-8

pandas           : 1.4.2
numpy            : 1.22.3
pytz             : 2022.1
dateutil         : 2.8.2
pip              : 22.0.4
setuptools       : 58.1.0
Cython           : None
pytest           : None
hypothesis       : None
sphinx           : None
blosc            : None
feather          : None
xlsxwriter       : None
lxml.etree       : None
html5lib         : None
pymysql          : None
psycopg2         : None
jinja2           : None
IPython          : None
pandas_datareader: None
bs4              : None
bottleneck       : None
brotli           : None
fastparquet      : None
fsspec           : None
gcsfs            : None
markupsafe       : None
matplotlib       : None
numba            : None
numexpr          : None
odfpy            : None
openpyxl         : None
pandas_gbq       : None
pyarrow          : None
pyreadstat       : None
pyxlsb           : None
s3fs             : None
scipy            : None
snappy           : None
sqlalchemy       : None
tables           : None
tabulate         : None
xarray           : None
xlrd             : None
xlwt             : None
zstandard        : None
</details>
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46848/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46848/timeline,
26,https://api.github.com/repos/pandas-dev/pandas/issues/46847,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46847/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46847/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46847/events,https://github.com/pandas-dev/pandas/pull/46847,1213061150,PR_kwDOAA0YD842qLY6,46847,REF: implement utc_val_to_local_val,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}, {'id': 60458168, 'node_id': 'MDU6TGFiZWw2MDQ1ODE2OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Timezones', 'name': 'Timezones', 'color': '5319e7', 'default': False, 'description': 'Timezone data dtype'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/92', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/92/labels', 'id': 7530006, 'node_id': 'MI_kwDOAA0YD84AcuYW', 'number': 92, 'title': '1.5', 'description': '', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 78, 'closed_issues': 690, 'state': 'open', 'created_at': '2021-12-31T21:51:13Z', 'updated_at': '2022-04-26T22:10:05Z', 'due_on': '2022-06-30T07:00:00Z', 'closed_at': None}",0,2022-04-23T01:34:36Z,2022-04-26T20:05:37Z,,MEMBER,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46847', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46847', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46847.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46847.patch', 'merged_at': None}","Some overlap with #46803.  I'm pretty happy with the perf impact, as the cases that are slowed down are the ones that are currently the fastest.

```
asv continuous -E virtualenv -f 1.01 a8968bfa 874d1ed4 --record-samples --append-samples -b tslibs.normalize -b tslibs.tslib.TimeIntsToPydatetime -b tslibs.period.TimeDT64ArrToPeriodArr -b tslibs.resolution
[...]
       before           after         ratio
     [a8968bfa]       [874d1ed4]
     <enh-nano-tzconversion>                 
+        89.6±3μs          122±2μs     1.36  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      8.93±0.5ms       12.1±0.6ms     1.35  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        85.0±4μs          109±4μs     1.28  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      8.40±0.5ms       10.5±0.7ms     1.25  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, datetime.timezone(datetime.timedelta(seconds=3600)))
+        74.1±4μs         85.5±3μs     1.15  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, None)
+     2.07±0.09μs      2.35±0.06μs     1.14  tslibs.normalize.Normalize.time_is_date_array_normalized(100, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+     1.24±0.06μs      1.41±0.03μs     1.14  tslibs.normalize.Normalize.time_is_date_array_normalized(100, datetime.timezone.utc)
+        75.4±5μs         85.1±1μs     1.13  tslibs.normalize.Normalize.time_is_date_array_normalized(10000, datetime.timezone.utc)
+      7.74±0.7ms       8.69±0.6ms     1.12  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, None)
+      7.65±0.3ms       8.57±0.2ms     1.12  tslibs.normalize.Normalize.time_is_date_array_normalized(1000000, datetime.timezone.utc)
+     1.32±0.08μs      1.46±0.05μs     1.11  tslibs.normalize.Normalize.time_is_date_array_normalized(100, None)
+         104±5μs          115±5μs     1.11  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, datetime.timezone(datetime.timedelta(seconds=3600)))
+        244±10μs          270±3μs     1.10  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 3000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         116±4μs          128±2μs     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        23.9±1ms       26.3±0.3ms     1.10  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 3000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      11.3±0.6ms       12.4±0.3ms     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      9.66±0.7ms       10.6±0.3ms     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      8.11±0.6ms       8.90±0.3ms     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, None)
+        85.7±2μs        93.9±10μs     1.10  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, datetime.timezone.utc)
+         203±4μs          222±2μs     1.09  tslibs.resolution.TimeResolution.time_get_resolution('m', 10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      8.20±0.5ms       8.96±0.3ms     1.09  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1000000, datetime.timezone.utc)
+      5.11±0.1μs       5.49±0.1μs     1.08  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         279±8μs          300±3μs     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        26.1±2ms       28.0±0.5ms     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 8000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         267±9μs         287±10μs     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 8000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      23.8±0.7ms       25.5±0.8ms     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         270±8μs          288±3μs     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 9000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        27.7±1ms       29.5±0.4ms     1.07  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 4006, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         284±8μs          302±6μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 4006, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        26.2±2ms         27.9±1ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 9000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         250±8μs          265±3μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        27.4±1ms       29.1±0.8ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         246±9μs          261±3μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      23.7±0.7ms         25.1±1ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      22.4±0.8ms       23.7±0.3ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2000, None)
+      26.2±0.8ms         27.7±1ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 7000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        25.9±1ms       27.3±0.3ms     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 6000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         249±9μs         263±20μs     1.06  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 6000, None)
+        87.8±4μs         92.6±1μs     1.06  tslibs.normalize.Normalize.time_normalize_i8_timestamps(10000, None)
+        246±10μs          259±3μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 1011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+        246±10μs          259±5μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         236±8μs          247±3μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2011, None)
+      24.0±0.7ms       25.2±0.3ms     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 1011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         250±3μs          262±3μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 6000, datetime.timezone.utc)
+         230±6μs          241±7μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2000, datetime.timezone.utc)
+         231±7μs          242±4μs     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 2000, None)
+      22.6±0.9ms       23.6±0.2ms     1.05  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2000, datetime.timezone.utc)
+     4.80±0.08μs       5.01±0.3μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         262±4μs          274±3μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 11000, None)
+        262±10μs          273±4μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 8000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      23.2±0.8ms       24.2±0.5ms     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2011, None)
+      3.70±0.1μs      3.86±0.04μs     1.04  tslibs.resolution.TimeResolution.time_get_resolution('D', 100, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      24.7±0.7ms       25.8±0.4ms     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 7000, datetime.timezone.utc)
+         260±4μs          271±3μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 9000, None)
+      24.8±0.6ms       25.8±0.2ms     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 7000, None)
+        26.4±1ms       27.4±0.3ms     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 12000, datetime.timezone(datetime.timedelta(seconds=3600)))
+         253±6μs          263±3μs     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 7000, None)
+      24.6±0.7ms       25.5±0.2ms     1.04  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 6000, None)
+        32.3±1ms       33.4±0.4ms     1.03  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 5000, datetime.timezone.utc)
+      23.3±0.6ms       24.1±0.2ms     1.03  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2011, datetime.timezone.utc)
+     2.43±0.06μs      2.51±0.04μs     1.03  tslibs.normalize.Normalize.time_normalize_i8_timestamps(100, datetime.timezone.utc)
+         346±6μs          357±5μs     1.03  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 5000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+      25.4±0.5ms       26.2±0.3ms     1.03  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 8000, datetime.timezone(datetime.timedelta(seconds=3600)))
+      5.07±0.2μs       5.22±0.5μs     1.03  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 8000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
+         266±7μs          274±5μs     1.03  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 9000, datetime.timezone(datetime.timedelta(seconds=3600)))
-        55.9±4ms       55.2±0.3ms     0.99  tslibs.resolution.TimeResolution.time_get_resolution('m', 1000000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        33.0±4μs       32.6±0.3μs     0.99  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 100, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-        32.1±3μs       31.6±0.2μs     0.99  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 100, datetime.timezone.utc)
-        535±30μs          526±7μs     0.98  tslibs.resolution.TimeResolution.time_get_resolution('D', 10000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      24.1±0.6ms       23.8±0.2ms     0.98  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 2011, datetime.timezone(datetime.timedelta(seconds=3600)))
-      7.05±0.8μs      6.94±0.08μs     0.98  tslibs.resolution.TimeResolution.time_get_resolution('s', 100, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        38.3±3μs       37.7±0.7μs     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 1, tzlocal())
-      3.47±0.3ms      3.41±0.06ms     0.98  tslibs.resolution.TimeResolution.time_get_resolution('ns', 100, tzlocal())
-      4.04±0.3ms      3.97±0.07ms     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 10000, datetime.timezone.utc)
-        42.1±5μs       41.4±0.4μs     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 100, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.81±0.1μs      1.78±0.09μs     0.98  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 11000, None)
-        29.1±3μs       28.5±0.3μs     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-      3.99±0.3ms      3.91±0.03ms     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 10000, None)
-      2.42±0.2ms      2.37±0.04ms     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 10000, None)
-     2.13±0.06μs      2.08±0.05μs     0.98  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 4000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        23.4±1ms       22.8±0.3ms     0.98  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 1000, datetime.timezone(datetime.timedelta(seconds=3600)))
-        345±10ms          337±4ms     0.98  tslibs.resolution.TimeResolution.time_get_resolution('h', 10000, tzlocal())
-        35.7±2μs       34.9±0.3μs     0.98  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 100, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        569±30μs          555±7μs     0.98  tslibs.resolution.TimeResolution.time_get_resolution('m', 10000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      7.64±0.6μs       7.45±0.2μs     0.98  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 4006, datetime.timezone(datetime.timedelta(seconds=3600)))
-        23.5±1ms       22.9±0.2ms     0.97  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 1011, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.40±0.06μs      1.36±0.02μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('m', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        577±60μs          562±9μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('s', 10000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        27.7±3ms       27.0±0.4ms     0.97  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 4000, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.09±0.07μs      1.06±0.01μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('us', 1, None)
-        351±10ms          341±4ms     0.97  tslibs.resolution.TimeResolution.time_get_resolution('us', 10000, tzlocal())
-        53.7±4ms       52.2±0.5ms     0.97  tslibs.resolution.TimeResolution.time_get_resolution('D', 1000000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.63±0.1μs      1.59±0.02μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('ns', 0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      1.56±0.2μs      1.52±0.03μs     0.97  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 0, tzlocal())
-      1.84±0.2μs      1.79±0.03μs     0.97  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 1, None)
-     2.36±0.05μs      2.29±0.04μs     0.97  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 2000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      8.33±0.2μs       8.08±0.2μs     0.97  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 5000, datetime.timezone(datetime.timedelta(seconds=3600)))
-         352±9ms          341±4ms     0.97  tslibs.resolution.TimeResolution.time_get_resolution('m', 10000, tzlocal())
-        349±20ms          338±6ms     0.97  tslibs.resolution.TimeResolution.time_get_resolution('s', 10000, tzlocal())
-     2.14±0.06μs      2.07±0.04μs     0.97  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-     1.01±0.09μs         976±20ns     0.97  tslibs.resolution.TimeResolution.time_get_resolution('us', 1, datetime.timezone.utc)
-        212±20μs          205±2μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('s', 10000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.67±0.1μs      1.62±0.01μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('s', 1, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-         254±5μs          245±3μs     0.97  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(10000, 3000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.31±0.3μs      2.23±0.05μs     0.97  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.82±0.2μs      1.76±0.04μs     0.97  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 6000, tzlocal())
-        37.3±3μs       36.0±0.4μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('s', 1, tzlocal())
-      1.64±0.1μs      1.59±0.03μs     0.97  tslibs.resolution.TimeResolution.time_get_resolution('s', 0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      1.53±0.2μs      1.48±0.03μs     0.96  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 0, None)
-      7.51±0.1μs       7.24±0.2μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 6000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      7.40±0.6μs      7.13±0.07μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 3000, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.72±0.04μs      1.65±0.03μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 7000, datetime.timezone.utc)
-      6.30±0.6μs      6.07±0.09μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('s', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.51±0.05μs      1.46±0.04μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('m', 1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.39±0.1μs      1.34±0.03μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('ns', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      2.52±0.3μs      2.43±0.05μs     0.96  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 1, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-     1.64±0.06μs      1.57±0.01μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('m', 0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      6.26±0.5μs      6.02±0.05μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('ns', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.73±0.05μs      1.66±0.04μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 9000, datetime.timezone.utc)
-      1.74±0.2μs      1.67±0.03μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 3000, datetime.timezone.utc)
-     1.70±0.05μs      1.63±0.02μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 6000, datetime.timezone.utc)
-      4.93±0.2μs       4.73±0.2μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 8000, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.84±0.05μs      1.76±0.04μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 6000, None)
-      4.99±0.1μs       4.79±0.1μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 6000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      6.48±0.5μs       6.22±0.1μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('h', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-     2.15±0.06μs      2.06±0.03μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 8000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-     2.37±0.03μs      2.28±0.07μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 5000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      4.91±0.1μs       4.71±0.1μs     0.96  tslibs.normalize.Normalize.time_normalize_i8_timestamps(1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.44±0.2μs      2.34±0.09μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 12000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      1.53±0.1μs      1.47±0.02μs     0.96  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 0, None)
-      1.50±0.2μs      1.44±0.03μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('s', 1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      6.28±0.1μs       6.01±0.1μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('D', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.40±0.2μs      2.29±0.03μs     0.96  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 7000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      2.18±0.2μs      2.09±0.06μs     0.96  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-     1.43±0.04μs      1.36±0.03μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('h', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      4.95±0.2μs      4.73±0.08μs     0.96  tslibs.normalize.Normalize.time_normalize_i8_timestamps(0, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.50±0.06μs      1.44±0.04μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('h', 1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      4.21±0.1μs      4.02±0.08μs     0.96  tslibs.resolution.TimeResolution.time_get_resolution('m', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.49±0.1μs      1.42±0.03μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('ns', 1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.56±0.2μs      1.49±0.02μs     0.95  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 0, tzlocal())
-        50.7±5μs       48.3±0.8μs     0.95  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 100, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.72±0.1μs      1.64±0.04μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 1000, datetime.timezone.utc)
-      4.98±0.7μs       4.75±0.1μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 1011, datetime.timezone(datetime.timedelta(seconds=3600)))
-        585±40μs          557±5μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('h', 10000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        24.6±2ms         23.4±2ms     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1000000, 3000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.84±0.1μs      1.75±0.04μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 4000, tzlocal())
-      1.71±0.1μs      1.62±0.04μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('ns', 1, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-     1.41±0.04μs      1.34±0.01μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('D', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      4.91±0.2μs       4.67±0.1μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 8000, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.11±0.03μs      1.06±0.02μs     0.95  tslibs.normalize.Normalize.time_is_date_array_normalized(0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      5.16±0.6μs      4.90±0.08μs     0.95  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.04±0.5μs       4.78±0.1μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 10000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.46±0.1μs      1.38±0.03μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('us', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        38.0±4μs       36.0±0.9μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('ns', 1, tzlocal())
-      1.50±0.2μs      1.42±0.02μs     0.95  tslibs.resolution.TimeResolution.time_get_resolution('us', 1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.89±0.2μs      1.80±0.04μs     0.95  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      2.19±0.1μs      2.07±0.03μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 1000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-     5.00±0.09μs       4.73±0.2μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 9000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      7.78±0.7μs       7.35±0.2μs     0.95  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 7000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.95±0.1μs       4.68±0.1μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 4000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      7.48±0.5μs       7.06±0.1μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 2000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.47±0.1μs      1.39±0.02μs     0.94  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 0, datetime.timezone.utc)
-      3.51±0.2μs       3.31±0.1μs     0.94  tslibs.normalize.Normalize.time_is_date_array_normalized(0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.01±0.1μs       4.72±0.2μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 11000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.80±0.6μs      4.52±0.04μs     0.94  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.78±0.2μs      1.67±0.03μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 2000, datetime.timezone.utc)
-      5.02±0.5μs       4.71±0.1μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 1000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.77±0.1μs      1.66±0.03μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 10000, datetime.timezone.utc)
-     2.21±0.09μs      2.08±0.05μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 1000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      5.01±0.5μs       4.70±0.1μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 2000, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.75±0.05μs      1.64±0.04μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 8000, datetime.timezone.utc)
-      4.98±0.5μs      4.66±0.06μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 12000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.21±0.1μs      3.94±0.09μs     0.94  tslibs.resolution.TimeResolution.time_get_resolution('s', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.11±0.4μs      4.79±0.06μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 3000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.48±0.2μs       2.33±0.1μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 2011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      4.30±0.2μs       4.02±0.1μs     0.94  tslibs.resolution.TimeResolution.time_get_resolution('h', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.00±0.1μs      1.87±0.03μs     0.94  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      2.54±0.2μs      2.37±0.06μs     0.94  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 1, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      5.09±0.6μs       4.76±0.1μs     0.94  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 4006, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.25±0.3μs      3.97±0.07μs     0.93  tslibs.resolution.TimeResolution.time_get_resolution('ns', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-     1.44±0.08μs      1.34±0.02μs     0.93  tslibs.resolution.TimeResolution.time_get_resolution('s', 0, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      5.09±0.2μs      4.75±0.07μs     0.93  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 5000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.91±0.1μs      1.78±0.04μs     0.93  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 1, datetime.timezone.utc)
-      2.19±0.1μs      2.04±0.06μs     0.93  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      6.52±0.6μs      6.06±0.08μs     0.93  tslibs.resolution.TimeResolution.time_get_resolution('us', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.41±0.1μs      2.24±0.04μs     0.93  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 1000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-        915±30ns         850±10ns     0.93  tslibs.normalize.Normalize.time_is_date_array_normalized(1, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      1.72±0.1μs      1.60±0.01μs     0.93  tslibs.resolution.TimeResolution.time_get_resolution('us', 1, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      5.05±0.1μs       4.68±0.2μs     0.93  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 6000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.88±0.1μs      1.74±0.02μs     0.93  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 7000, tzlocal())
-     1.66±0.09μs      1.54±0.03μs     0.92  tslibs.resolution.TimeResolution.time_get_resolution('h', 0, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      4.36±0.6μs      4.03±0.08μs     0.92  tslibs.resolution.TimeResolution.time_get_resolution('ns', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.83±0.5μs       4.46±0.1μs     0.92  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.10±0.1μs      4.70±0.06μs     0.92  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 1011, datetime.timezone(datetime.timedelta(seconds=3600)))
-      1.76±0.2μs      1.62±0.03μs     0.92  tslibs.resolution.TimeResolution.time_get_resolution('h', 1, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      4.27±0.2μs      3.93±0.09μs     0.92  tslibs.resolution.TimeResolution.time_get_resolution('D', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.47±0.8μs       4.11±0.1μs     0.92  tslibs.resolution.TimeResolution.time_get_resolution('us', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.38±0.4μs      4.95±0.05μs     0.92  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('timestamp', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.54±0.3μs      2.33±0.06μs     0.92  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 1011, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      1.91±0.2μs      1.75±0.05μs     0.92  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 1011, tzlocal())
-      4.38±0.4μs       4.01±0.1μs     0.91  tslibs.resolution.TimeResolution.time_get_resolution('s', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.54±0.2μs      2.32±0.09μs     0.91  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 9000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-      1.58±0.1μs      1.44±0.02μs     0.91  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('date', 0, None)
-      5.13±0.2μs       4.66±0.1μs     0.91  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 1000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.20±0.4μs      4.71±0.09μs     0.91  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 2011, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.29±0.2μs      2.07±0.04μs     0.90  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 2011, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-      4.36±0.2μs      3.94±0.07μs     0.90  tslibs.resolution.TimeResolution.time_get_resolution('m', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.25±0.1μs       3.84±0.1μs     0.90  tslibs.resolution.TimeResolution.time_get_resolution('h', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      4.30±0.4μs      3.87±0.05μs     0.90  tslibs.resolution.TimeResolution.time_get_resolution('us', 0, datetime.timezone(datetime.timedelta(seconds=3600)))
-      3.67±0.2μs       3.30±0.1μs     0.90  tslibs.normalize.Normalize.time_is_date_array_normalized(1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.33±0.5μs       4.78±0.1μs     0.90  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('time', 1, datetime.timezone(datetime.timedelta(seconds=3600)))
-      3.45±0.3ms      3.09±0.04ms     0.90  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 10000, tzfile('/usr/share/zoneinfo/Asia/Tokyo'))
-        40.2±3μs         36.0±1μs     0.89  tslibs.resolution.TimeResolution.time_get_resolution('m', 1, tzlocal())
-      7.90±0.8μs       6.97±0.1μs     0.88  tslibs.resolution.TimeResolution.time_get_resolution('m', 100, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        233±20μs          206±2μs     0.88  tslibs.resolution.TimeResolution.time_get_resolution('us', 10000, datetime.timezone(datetime.timedelta(seconds=3600)))
-        22.4±2ms       19.7±0.2ms     0.88  tslibs.resolution.TimeResolution.time_get_resolution('us', 1000000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      5.33±0.5μs       4.65±0.5μs     0.87  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(0, 10000, datetime.timezone(datetime.timedelta(seconds=3600)))
-      2.39±0.2μs      2.07±0.08μs     0.87  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(1, 3000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
-        398±40ms          345±2ms     0.87  tslibs.tslib.TimeIntsToPydatetime.time_ints_to_pydatetime('datetime', 10000, tzlocal())
-      8.41±0.7μs       7.22±0.6μs     0.86  tslibs.period.TimeDT64ArrToPeriodArr.time_dt64arr_to_periodarr(100, 2011, datetime.timezone(datetime.timedelta(seconds=3600)))
-      7.20±0.4μs       6.16±0.1μs     0.86  tslibs.resolution.TimeResolution.time_get_resolution('m', 100, datetime.timezone(datetime.timedelta(seconds=3600)))
-        240±20μs          205±2μs     0.85  tslibs.resolution.TimeResolution.time_get_resolution('ns', 10000, datetime.timezone(datetime.timedelta(seconds=3600)))
-        674±60μs          543±8μs     0.81  tslibs.resolution.TimeResolution.time_get_resolution('ns', 10000, <DstTzInfo 'US/Pacific' LMT-1 day, 16:07:00 STD>)
```","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46847/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46847/timeline,
27,https://api.github.com/repos/pandas-dev/pandas/issues/46846,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46846/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46846/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46846/events,https://github.com/pandas-dev/pandas/pull/46846,1213035674,PR_kwDOAA0YD842qIfg,46846,Try to fix groupby_valuecount,"{'login': 'DongqiWu', 'id': 73769392, 'node_id': 'MDQ6VXNlcjczNzY5Mzky', 'avatar_url': 'https://avatars.githubusercontent.com/u/73769392?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/DongqiWu', 'html_url': 'https://github.com/DongqiWu', 'followers_url': 'https://api.github.com/users/DongqiWu/followers', 'following_url': 'https://api.github.com/users/DongqiWu/following{/other_user}', 'gists_url': 'https://api.github.com/users/DongqiWu/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/DongqiWu/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/DongqiWu/subscriptions', 'organizations_url': 'https://api.github.com/users/DongqiWu/orgs', 'repos_url': 'https://api.github.com/users/DongqiWu/repos', 'events_url': 'https://api.github.com/users/DongqiWu/events{/privacy}', 'received_events_url': 'https://api.github.com/users/DongqiWu/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 233160, 'node_id': 'MDU6TGFiZWwyMzMxNjA=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Groupby', 'name': 'Groupby', 'color': '729FCF', 'default': False, 'description': None}, {'id': 57296398, 'node_id': 'MDU6TGFiZWw1NzI5NjM5OA==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Algos', 'name': 'Algos', 'color': 'eb6420', 'default': False, 'description': 'Non-arithmetic algos: value_counts, factorize, sorting, isin, clip, shift, diff'}]",open,False,,[],,1,2022-04-23T01:05:32Z,2022-04-25T21:24:04Z,,NONE,,False,"{'url': 'https://api.github.com/repos/pandas-dev/pandas/pulls/46846', 'html_url': 'https://github.com/pandas-dev/pandas/pull/46846', 'diff_url': 'https://github.com/pandas-dev/pandas/pull/46846.diff', 'patch_url': 'https://github.com/pandas-dev/pandas/pull/46846.patch', 'merged_at': None}","- [BUG: fixed subset parameter of DataFrameGroupBy.value_counts has no effect] closes #46383  
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46846/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46846/timeline,
28,https://api.github.com/repos/pandas-dev/pandas/issues/46844,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46844/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46844/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46844/events,https://github.com/pandas-dev/pandas/issues/46844,1212926885,I_kwDOAA0YD85IS8ul,46844,REF: avoid object-casting in EA methods,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 76811, 'node_id': 'MDU6TGFiZWw3NjgxMQ==', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Bug', 'name': 'Bug', 'color': 'e10c02', 'default': False, 'description': None}, {'id': 1954720290, 'node_id': 'MDU6TGFiZWwxOTU0NzIwMjkw', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Needs%20Triage', 'name': 'Needs Triage', 'color': '0052cc', 'default': False, 'description': 'Issue that has not been reviewed by a pandas team member'}]",open,False,,[],,0,2022-04-22T23:04:41Z,2022-04-22T23:04:57Z,,MEMBER,,,,"The following EA methods do an self.astype(object), can likely be improved upon by e.g. round-tripping through factorize:

- [ ] unique
- [ ] fillna
- [ ] searchsorted
- [ ] _fill_mask_inplace
","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46844/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46844/timeline,
29,https://api.github.com/repos/pandas-dev/pandas/issues/46843,https://api.github.com/repos/pandas-dev/pandas,https://api.github.com/repos/pandas-dev/pandas/issues/46843/labels{/name},https://api.github.com/repos/pandas-dev/pandas/issues/46843/comments,https://api.github.com/repos/pandas-dev/pandas/issues/46843/events,https://github.com/pandas-dev/pandas/issues/46843,1212918358,I_kwDOAA0YD85IS6pW,46843,REF: avoid passing `self` as arg from ExtensionArray methods,"{'login': 'jbrockmendel', 'id': 8078968, 'node_id': 'MDQ6VXNlcjgwNzg5Njg=', 'avatar_url': 'https://avatars.githubusercontent.com/u/8078968?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jbrockmendel', 'html_url': 'https://github.com/jbrockmendel', 'followers_url': 'https://api.github.com/users/jbrockmendel/followers', 'following_url': 'https://api.github.com/users/jbrockmendel/following{/other_user}', 'gists_url': 'https://api.github.com/users/jbrockmendel/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jbrockmendel/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jbrockmendel/subscriptions', 'organizations_url': 'https://api.github.com/users/jbrockmendel/orgs', 'repos_url': 'https://api.github.com/users/jbrockmendel/repos', 'events_url': 'https://api.github.com/users/jbrockmendel/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jbrockmendel/received_events', 'type': 'User', 'site_admin': False}","[{'id': 127681, 'node_id': 'MDU6TGFiZWwxMjc2ODE=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Refactor', 'name': 'Refactor', 'color': 'FCE94F', 'default': False, 'description': 'Internal refactoring of code'}, {'id': 211029535, 'node_id': 'MDU6TGFiZWwyMTEwMjk1MzU=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/Clean', 'name': 'Clean', 'color': '207de5', 'default': False, 'description': None}, {'id': 849023693, 'node_id': 'MDU6TGFiZWw4NDkwMjM2OTM=', 'url': 'https://api.github.com/repos/pandas-dev/pandas/labels/ExtensionArray', 'name': 'ExtensionArray', 'color': '6138b5', 'default': False, 'description': 'Extending pandas with custom dtypes or arrays.'}]",open,False,,[],"{'url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32', 'html_url': 'https://github.com/pandas-dev/pandas/milestone/32', 'labels_url': 'https://api.github.com/repos/pandas-dev/pandas/milestones/32/labels', 'id': 933188, 'node_id': 'MDk6TWlsZXN0b25lOTMzMTg4', 'number': 32, 'title': 'Contributions Welcome', 'description': 'Changes that would be nice to have in the next release. These issues are not blocking. They will be pushed to the next release if no one has time to fix them.', 'creator': {'login': 'jreback', 'id': 953992, 'node_id': 'MDQ6VXNlcjk1Mzk5Mg==', 'avatar_url': 'https://avatars.githubusercontent.com/u/953992?v=4', 'gravatar_id': '', 'url': 'https://api.github.com/users/jreback', 'html_url': 'https://github.com/jreback', 'followers_url': 'https://api.github.com/users/jreback/followers', 'following_url': 'https://api.github.com/users/jreback/following{/other_user}', 'gists_url': 'https://api.github.com/users/jreback/gists{/gist_id}', 'starred_url': 'https://api.github.com/users/jreback/starred{/owner}{/repo}', 'subscriptions_url': 'https://api.github.com/users/jreback/subscriptions', 'organizations_url': 'https://api.github.com/users/jreback/orgs', 'repos_url': 'https://api.github.com/users/jreback/repos', 'events_url': 'https://api.github.com/users/jreback/events{/privacy}', 'received_events_url': 'https://api.github.com/users/jreback/received_events', 'type': 'User', 'site_admin': False}, 'open_issues': 988, 'closed_issues': 841, 'state': 'open', 'created_at': '2015-01-13T10:53:19Z', 'updated_at': '2022-04-26T01:14:35Z', 'due_on': None, 'closed_at': None}",0,2022-04-22T23:02:06Z,2022-04-25T19:33:13Z,,MEMBER,,,,"The following functions are called from ExtensionArray methods with `self` as the first argument:

- [ ] nargminmax
- [ ] format_object_summary
- [ ] rank
- [ ] mode

This implicitly means that these functions are depending on EA implementation details (or in some cases just casting to object), which is a code smell.  These should be refactored to use e.g. _values_for_argsort, _values_for_factorize, ...

<b>Update</b> Also in 

- [ ] NDArrayBackedExtensioNArray.argmin
- [ ] NDArrayBackedExtensioNArray.argmax","{'url': 'https://api.github.com/repos/pandas-dev/pandas/issues/46843/reactions', 'total_count': 0, '+1': 0, '-1': 0, 'laugh': 0, 'hooray': 0, 'confused': 0, 'heart': 0, 'rocket': 0, 'eyes': 0}",https://api.github.com/repos/pandas-dev/pandas/issues/46843/timeline,
